### ISSUE TITLE
It would be nice if the README.md detailed the distinctions between the 2 hex files in the repository. 

### ISSUE THREAD

**Issue by jedimatt42** [go4retro/HEXTIr#34]
Arduino build chains get out of date, and it is nice that there appears to be binaries in here to program directly. But they appear to be for different boards, with no explicit documentation of purpose.

Are they built with all the options? as there is info about enabling and disabling different features to fit in different chips.

Which wiring diagrams do they match to?

Please update the documentation.

**Comment by go4retro** [comment]
v1 PCB build config and binaries were missing non drive peripherals.  Refreshed builds and updated README.  Let me know if the new README is sufficient, or make a pull request if desired.
