### ISSUE TITLE
This wiring doesn't work with the current or rev v0.9.3.3 328p-arduino hex files

### ISSUE THREAD

**Issue by jedimatt42** [go4retro/HEXTIr#35]
https://github.com/go4retro/HEXTIr/blob/00074e3dfe0678920cc521dee59f99fec876bfa7/doc/arduino/Assembly%20Instructions.txt#L9

Arduino L1 needs to go to Arduino pin 7
and then double check HEX-BAV and HEX-HSK, one goes to arduino pin 2. 

These pictures floated in a circle and work with the committed hex file: 

- https://postlmg.cc/V0JNJZc4
- https://postimg.cc/kVCDTyxX

**Comment by go4retro** [comment]
Thanks for noting.  Those instructions were created early in development, and we moved the HSK pin to take advantage of a sleep capability.
