### ISSUE TITLE
English weekdays

### ISSUE THREAD

**Issue by polluks** [go4retro/HEXTIr#36]
https://github.com/go4retro/HEXTIr/blob/51ea22df26cbc6beedb13e90dd0e530246948a9c/BASIC/CC40/CLOCK.B40#L2
110 DATA "Sa","Su","Mo","Tu","We","Th","Fr"

**Comment by go4retro** [comment]
Can you make the update and submit a patch? I'm in the midst of other things at present, and this code came from someone else.
JIm
